# Generated by Django 6.0.4 on 2026-07-30 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_price', models.DecimalField(decimal_places=2, default=5.89, max_digits=6)),
                ('daily_goal', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('monthly_goal', models.DecimalField(decimal_places=2, default=6000, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
