# Generated by Django 6.0.4 on 2026-08-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
