# Generated by Django 6.0.4 on 2026-08-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='quote_art',
            field=models.TextField(blank=True, help_text='Base64 data URL da arte de fundo do PDF de orcamentos (A4 ou PNG/JPG)', null=True),
        ),
    ]
