# Generated by Django 6.0.4 on 2026-08-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings_quote_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Nome exibido no PDF de orcamentos', max_length=120, null=True),
        ),
    ]
