services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: uber_control
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: uber123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: