# Generated by Django 6.0.4 on 2026-07-30 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_km', models.IntegerField()),
                ('end_km', models.IntegerField(blank=True, null=True)),
                ('fuel_level_start', models.CharField(blank=True, max_length=50, null=True)),
                ('uber_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pix_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tolls_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_km', models.IntegerField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
