# Generated by Django 6.0.4 on 2026-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='user',
        ),
        migrations.AddField(
            model_name='journey',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journey',
            name='paused_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
