# Generated by Django 6.0.4 on 2026-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_remove_journey_user_journey_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='cash_on_hand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
