# Generated by Django 6.0.4 on 2026-08-02 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('origin', models.TextField()),
                ('destination', models.TextField()),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('origin_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dest_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dest_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_cash_pix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_card', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
