# Generated by Django 6.0.4 on 2026-08-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.TextField(blank=True, help_text='Base64 data URL da foto do veiculo', null=True),
        ),
    ]
