# Generated by Django 6.0.4 on 2026-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fueling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling',
            name='avg_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='cost_per_km',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='km_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
